[Refactor]: create leave validation
copods/leave-tracking-tool-backend pull request #63
Opened 2024-06-19 05:48 UTC by kalash-copods

added overlapping leaves validation in create leave api

2024-06-19 12:13 UTC, anuragP04 requested changes

2024-06-19 12:13 UTC, anuragP04 commented on LeaveTrackingApp/views/leaves_views.py
> +                return JsonResponse({'error': 'Leave overlaps with existing leave'}, status=status.HTTP_400_BAD_REQUEST)
we can update this message to: You have already applied leave for some of these days

2024-06-19 12:13 UTC, anuragP04 commented on LeaveTrackingApp/utils.py
> +        ( (Q(start_date__lte=start_date ) & Q(end_date__gte=start_date)) | Q(start_date__lte=end_date ) )
let's discuss this logic in person

2024-06-20 06:18 UTC, kalash-copods commented on LeaveTrackingApp/utils.py
> +        ( (Q(start_date__lte=start_date ) & Q(end_date__gte=start_date)) | Q(start_date__lte=end_date ) )
now covers all overlap scenarios and fixed where leave doesn't overlaps but still gets counted

2024-06-20 06:34 UTC, anuragP04 approved these changes

2024-06-20 06:34 UTC, merged