[Merge]: Dev-mirror to Dev
copods/leave-tracking-tool-backend pull request #90
Opened 2024-07-08 10:10 UTC by kalash-copods

2024-07-18 06:45 UTC, arpita-20 approved these changes

2024-07-18 09:27 UTC, chandani-copods commented on LeaveTrackingApp/serializers/leave_serializers.py
> +
If not required, remove this commented code

2024-07-18 09:55 UTC, kalash-copods commented on LeaveTrackingApp/serializers/leave_serializers.py
> +
needed for future reference, added TODO comment

2024-07-18 09:57 UTC, chandani-copods commented on LeaveTrackingApp/utils.py
>          leave_wfh_for_year = {
look up naming convention .

2024-07-18 10:05 UTC, chandani-copods commented on UserApp/serializers/user_serializers.py
> +    def to_representation(self, instance):
naming

2024-07-18 10:08 UTC, chandani-copods approved these changes

2024-07-18 10:14 UTC, kalash-copods commented on UserApp/serializers/user_serializers.py
> +    def to_representation(self, instance):
this function is from django serializers. I have overridden it

2024-07-18 11:32 UTC, richa-copods requested changes

2024-07-18 11:42 UTC, kalash-copods commented on LeaveTrackingApp/models.py
> +    STATUS_CHOICES = [
resolved

2024-07-19 06:54 UTC, richa-copods approved these changes

2024-07-19 06:56 UTC, merged