[Feat]: year calendar apis
copods/leave-tracking-tool-backend pull request #93
Opened 2024-07-08 19:23 UTC by kalash-copods

created update api and modified create and get api for year calendar.
modified year calendar schema and serializers

2024-07-16 10:41 UTC, richa-copods requested changes

2024-07-16 10:41 UTC, richa-copods commented on LeaveTrackingApp/views/calendar_and_policy_views.py
> +
Remove extra line

2024-07-16 11:30 UTC, kalash-copods commented on LeaveTrackingApp/serializers/calendar_and_policy_serializers.py
> +        print(holiday_data)
resolved

2024-07-16 11:45 UTC, kalash-copods commented on LeaveTrackingApp/views/calendar_and_policy_views.py
> +            if year:
already handled it in create api

2024-07-16 11:57 UTC, kalash-copods commented on LeaveTrackingApp/views/calendar_and_policy_views.py
> +                    year_calendar = yearCalendar.objects.filter(status__in=['approved', 'draft', 'sent_for_approval'], year=year).order_by('-updated_at').first()
resolved

2024-07-16 12:00 UTC, kalash-copods commented on LeaveTrackingApp/views/calendar_and_policy_views.py
> +        try:
will be handled in frontend by clearing the populated data and edit the existing one only (suggested by Aditya), as we are having only one draft state, deleting from db would be of no use

2024-07-16 12:09 UTC, kalash-copods commented on LeaveTrackingApp/views/calendar_and_policy_views.py
> +            if not year_calendar_data.get('status') or year_calendar_data['status'] != 'Draft':
resolved

2024-07-16 12:11 UTC, kalash-copods commented on LeaveTrackingApp/views/calendar_and_policy_views.py
> +
resolved

2024-07-17 09:04 UTC, richa-copods approved these changes

2024-07-17 09:04 UTC, merged